[package]
name = "OhBoyGUI"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["tokio"] }
rfd = "0.15.0"
tokio = { version = "~1.38", features = ["fs", "rt", "process"] }
